spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cleartrip?useSSL=false
    username: root
    password: root!123
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialectallow-bean-definition-overriding=true
  main:
    allow-bean-definition-overriding: true